apiVersion: secrets.k8s.k.io/v1
kind: GeneratedSecret
metadata:
  name: {{ include "app.generateName" (dict "root" . "suffix" "generated-secrets") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    {{ include "app.argocdAnnotations" (dict "root" . "wave" 5) | nindent 4 }}
spec:
  deleteSecretOnDelete: true
  keys:
    - name: secret-key-base
      type: Hex
      length: 128
    - name: encryption-primary-key
      type: Alphanumeric
      length: 32
    - name: encryption-deterministic-key
      type: Alphanumeric
      length: 32
    - name: encryption-key-derivation-salt
      type: Alphanumeric
      length: 32
