apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "app.generateName" (dict "root" . "suffix" "https-redirect") }}
  namespace: {{ .Release.Namespace }}
spec:
  redirectScheme:
    scheme: https
    permanent: true
