apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.generateName" (dict "root" . "suffix" "web") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    {{- include "app.selectorLabels" . | nindent 4 }}
    krystal.io/component: web
  annotations:
    {{- include "app.argocdAnnotations" (dict "root" . "wave" 10) | nindent 4 }}
spec:
  type: {{ .Values.services.web.type | default "ClusterIP" }}
  externalTrafficPolicy: {{ .Values.services.web.externalTrafficPolicy }}
  ports:
    - name: http
      port: {{ .Values.services.web.port | default 80 }}
      protocol: TCP
      targetPort: http
    {{- if .Values.prometheus.enabled }}
    - name: metrics
      port: {{ .Values.prometheus.defaultExporterPort }}
      protocol: TCP
      targetPort: metrics
    {{- end }}
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
    krystal.io/component: web
