{{- if eq .Values.postgres.mode "builtin" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.generateName" (dict "root" . "suffix" "postgres") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    {{ include "app.argocdAnnotations" (dict "root" . "wave" 1) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
    component: postgres
{{- end }}
