{{- if eq .Values.redis.mode "builtin" }}
apiVersion: secrets.k8s.k.io/v1
kind: GeneratedSecret
metadata:
  name: {{ include "app.generateName" (dict "root" . "suffix" "redis") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    {{ include "app.argocdAnnotations" (dict "root" . "wave" 1) | nindent 4 }}
spec:
  deleteSecretOnDelete: true
  keys:
    - name: password
      type: Alphanumeric
      length: 24
{{- end }}
